#include "hmi_layout_store.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_log.h"
#include "cJSON.h"

#define HMI_LAYOUT_PATH "/spiffs/hmi_layout.json"
#define HMI_MAX_LAYOUT_BYTES (96 * 1024)

static const char *TAG = "hmi_layout_store";

static const char *s_default_layout =
"{\n"
"  \"version\": 2,\n"
"  \"startupPage\": \"Main\",\n"
"  \"scriptTick\": { \"enabled\": false, \"rateMs\": 250, \"function\": \"OnPanelTick\" },\n"
"  \"screen\": {\n"
"    \"width\": 800,\n"
"    \"height\": 480,\n"
"    \"background\": \"#101828\"\n"
"  },\n"
"  \"pages\": [\n"
"    {\n"
"      \"id\": \"Main\",\n"
"      \"name\": \"Main\",\n"
"      \"widgets\": [\n"
"        {\n"
"          \"id\": \"title\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 20,\n"
"          \"y\": 14,\n"
"          \"w\": 430,\n"
"          \"h\": 42,\n"
"          \"props\": {\n"
"            \"label\": \"PiLab Panel S3 Factory Demo\",\n"
"            \"pin\": \"Factory_Title\",\n"
"            \"color\": \"#FFFFFF\",\n"
"            \"fontSize\": 28\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"heartbeat\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 714,\n"
"          \"y\": 14,\n"
"          \"w\": 66,\n"
"          \"h\": 70,\n"
"          \"props\": {\n"
"            \"label\": \"HB\",\n"
"            \"pin\": \"Panel_Heartbeat\",\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"status\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 24,\n"
"          \"y\": 62,\n"
"          \"w\": 560,\n"
"          \"h\": 36,\n"
"          \"props\": {\n"
"            \"label\": \"Status\",\n"
"            \"pin\": \"Script_Status\",\n"
"            \"color\": \"#FACC15\",\n"
"            \"fontSize\": 21\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"start_stop\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 30,\n"
"          \"y\": 118,\n"
"          \"w\": 164,\n"
"          \"h\": 72,\n"
"          \"events\": {\n"
"            \"onClick\": \"StartStop_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"START / STOP\",\n"
"            \"pin\": \"Run_Command\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#0EA5E9\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"stop\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 210,\n"
"          \"y\": 118,\n"
"          \"w\": 112,\n"
"          \"h\": 72,\n"
"          \"events\": {\n"
"            \"onClick\": \"Stop_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"STOP\",\n"
"            \"pin\": \"Run_Command\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#EF4444\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"motor_led\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 348,\n"
"          \"y\": 112,\n"
"          \"w\": 112,\n"
"          \"h\": 88,\n"
"          \"props\": {\n"
"            \"label\": \"Motor\",\n"
"            \"pin\": \"Motor_Running\",\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"pump_led\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 478,\n"
"          \"y\": 112,\n"
"          \"w\": 112,\n"
"          \"h\": 88,\n"
"          \"props\": {\n"
"            \"label\": \"Pump\",\n"
"            \"pin\": \"Pump_Enable\",\n"
"            \"color\": \"#38BDF8\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"speed_pv\",\n"
"          \"type\": \"readout\",\n"
"          \"x\": 610,\n"
"          \"y\": 112,\n"
"          \"w\": 160,\n"
"          \"h\": 88,\n"
"          \"props\": {\n"
"            \"label\": \"Speed PV\",\n"
"            \"pin\": \"Motor_Speed_PV\",\n"
"            \"unit\": \" rpm\",\n"
"            \"decimals\": 0,\n"
"            \"min\": 0,\n"
"            \"max\": 5000,\n"
"            \"color\": \"#38BDF8\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"speed_sp\",\n"
"          \"type\": \"setpoint\",\n"
"          \"x\": 30,\n"
"          \"y\": 222,\n"
"          \"w\": 180,\n"
"          \"h\": 96,\n"
"          \"events\": {\n"
"            \"onChange\": \"SpeedSetpoint_Changed\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"Speed SP\",\n"
"            \"pin\": \"Motor_Speed_SP\",\n"
"            \"unit\": \" rpm\",\n"
"            \"min\": 0,\n"
"            \"max\": 5000,\n"
"            \"step\": 250,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#F97316\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"auto_toggle\",\n"
"          \"type\": \"toggle\",\n"
"          \"x\": 232,\n"
"          \"y\": 226,\n"
"          \"w\": 150,\n"
"          \"h\": 86,\n"
"          \"events\": {\n"
"            \"onChange\": \"AutoMode_Changed\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"Auto\",\n"
"            \"pin\": \"Auto_Mode\",\n"
"            \"color\": \"#A78BFA\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"fault_led\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 405,\n"
"          \"y\": 222,\n"
"          \"w\": 110,\n"
"          \"h\": 92,\n"
"          \"props\": {\n"
"            \"label\": \"Fault\",\n"
"            \"pin\": \"Fault_Active\",\n"
"            \"color\": \"#F43F5E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"temp_pv\",\n"
"          \"type\": \"readout\",\n"
"          \"x\": 540,\n"
"          \"y\": 222,\n"
"          \"w\": 110,\n"
"          \"h\": 92,\n"
"          \"props\": {\n"
"            \"label\": \"Temp\",\n"
"            \"pin\": \"Temp_PV\",\n"
"            \"unit\": \" C\",\n"
"            \"decimals\": 1,\n"
"            \"min\": 0,\n"
"            \"max\": 100,\n"
"            \"color\": \"#F59E0B\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"uptime\",\n"
"          \"type\": \"readout\",\n"
"          \"x\": 668,\n"
"          \"y\": 222,\n"
"          \"w\": 104,\n"
"          \"h\": 92,\n"
"          \"props\": {\n"
"            \"label\": \"Uptime\",\n"
"            \"pin\": \"Panel_Uptime_s\",\n"
"            \"unit\": \" s\",\n"
"            \"decimals\": 0,\n"
"            \"min\": 0,\n"
"            \"max\": 1000000,\n"
"            \"color\": \"#CBD5E1\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"to_process\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 30,\n"
"          \"y\": 350,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"ProcessPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"PROCESS\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#16A34A\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"to_diag\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 200,\n"
"          \"y\": 350,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"DiagnosticsPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"DIAG\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#64748B\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"alarm_reset\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 370,\n"
"          \"y\": 350,\n"
"          \"w\": 166,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"AlarmReset_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"RESET ALARM\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#7C3AED\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"note\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 555,\n"
"          \"y\": 348,\n"
"          \"w\": 222,\n"
"          \"h\": 62,\n"
"          \"props\": {\n"
"            \"label\": \"Tap setpoints for numeric keypad.\",\n"
"            \"color\": \"#94A3B8\",\n"
"            \"fontSize\": 17\n"
"          }\n"
"        }\n"
"      ]\n"
"    },\n"
"    {\n"
"      \"id\": \"Process\",\n"
"      \"name\": \"Process\",\n"
"      \"widgets\": [\n"
"        {\n"
"          \"id\": \"process_title\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 24,\n"
"          \"y\": 14,\n"
"          \"w\": 360,\n"
"          \"h\": 42,\n"
"          \"props\": {\n"
"            \"label\": \"Process View\",\n"
"            \"color\": \"#FFFFFF\",\n"
"            \"fontSize\": 28\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"status2\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 24,\n"
"          \"y\": 62,\n"
"          \"w\": 520,\n"
"          \"h\": 34,\n"
"          \"props\": {\n"
"            \"label\": \"Status\",\n"
"            \"pin\": \"Script_Status\",\n"
"            \"color\": \"#FACC15\",\n"
"            \"fontSize\": 20\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"tank\",\n"
"          \"type\": \"tank\",\n"
"          \"x\": 38,\n"
"          \"y\": 115,\n"
"          \"w\": 160,\n"
"          \"h\": 250,\n"
"          \"props\": {\n"
"            \"label\": \"Tank\",\n"
"            \"pin\": \"Tank_Level\",\n"
"            \"unit\": \" %\",\n"
"            \"min\": 0,\n"
"            \"max\": 100,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#06B6D4\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"level_sp\",\n"
"          \"type\": \"setpoint\",\n"
"          \"x\": 226,\n"
"          \"y\": 120,\n"
"          \"w\": 170,\n"
"          \"h\": 94,\n"
"          \"events\": {\n"
"            \"onChange\": \"LevelSetpoint_Changed\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"Level SP\",\n"
"            \"pin\": \"Tank_Level_SP\",\n"
"            \"unit\": \" %\",\n"
"            \"min\": 0,\n"
"            \"max\": 100,\n"
"            \"step\": 5,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"flow\",\n"
"          \"type\": \"gauge\",\n"
"          \"x\": 226,\n"
"          \"y\": 245,\n"
"          \"w\": 210,\n"
"          \"h\": 100,\n"
"          \"props\": {\n"
"            \"label\": \"Flow\",\n"
"            \"pin\": \"Flow_PV\",\n"
"            \"unit\": \" L/min\",\n"
"            \"min\": 0,\n"
"            \"max\": 100,\n"
"            \"decimals\": 1,\n"
"            \"color\": \"#38BDF8\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"pressure\",\n"
"          \"type\": \"gauge\",\n"
"          \"x\": 462,\n"
"          \"y\": 120,\n"
"          \"w\": 210,\n"
"          \"h\": 100,\n"
"          \"props\": {\n"
"            \"label\": \"Pressure\",\n"
"            \"pin\": \"Pressure_PV\",\n"
"            \"unit\": \" kPa\",\n"
"            \"min\": 0,\n"
"            \"max\": 500,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#A78BFA\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"temp_sp\",\n"
"          \"type\": \"setpoint\",\n"
"          \"x\": 462,\n"
"          \"y\": 245,\n"
"          \"w\": 170,\n"
"          \"h\": 94,\n"
"          \"events\": {\n"
"            \"onChange\": \"TempSetpoint_Changed\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"Temp SP\",\n"
"            \"pin\": \"Temp_SP\",\n"
"            \"unit\": \" C\",\n"
"            \"min\": 0,\n"
"            \"max\": 100,\n"
"            \"step\": 1,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#F97316\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"valve\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 670,\n"
"          \"y\": 120,\n"
"          \"w\": 92,\n"
"          \"h\": 88,\n"
"          \"props\": {\n"
"            \"label\": \"Valve\",\n"
"            \"pin\": \"Valve_Open\",\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"batch\",\n"
"          \"type\": \"readout\",\n"
"          \"x\": 670,\n"
"          \"y\": 245,\n"
"          \"w\": 92,\n"
"          \"h\": 94,\n"
"          \"props\": {\n"
"            \"label\": \"Batch\",\n"
"            \"pin\": \"Batch_Count\",\n"
"            \"unit\": \"\",\n"
"            \"min\": 0,\n"
"            \"max\": 9999,\n"
"            \"decimals\": 0,\n"
"            \"color\": \"#FACC15\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"main_btn\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 36,\n"
"          \"y\": 392,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"MainPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"MAIN\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#0EA5E9\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"diag_btn\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 206,\n"
"          \"y\": 392,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"DiagnosticsPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"DIAG\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#64748B\"\n"
"          }\n"
"        }\n"
"      ]\n"
"    },\n"
"    {\n"
"      \"id\": \"Diagnostics\",\n"
"      \"name\": \"Diagnostics\",\n"
"      \"widgets\": [\n"
"        {\n"
"          \"id\": \"diag_title\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 24,\n"
"          \"y\": 18,\n"
"          \"w\": 420,\n"
"          \"h\": 42,\n"
"          \"props\": {\n"
"            \"label\": \"Diagnostics / Runtime\",\n"
"            \"color\": \"#FFFFFF\",\n"
"            \"fontSize\": 28\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"diag_status\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 24,\n"
"          \"y\": 68,\n"
"          \"w\": 610,\n"
"          \"h\": 34,\n"
"          \"props\": {\n"
"            \"label\": \"Status\",\n"
"            \"pin\": \"Script_Status\",\n"
"            \"color\": \"#FACC15\",\n"
"            \"fontSize\": 19\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"heartbeat_diag\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 688,\n"
"          \"y\": 20,\n"
"          \"w\": 72,\n"
"          \"h\": 76,\n"
"          \"props\": {\n"
"            \"label\": \"HB\",\n"
"            \"pin\": \"Panel_Heartbeat\",\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"uptime_diag\",\n"
"          \"type\": \"readout\",\n"
"          \"x\": 35,\n"
"          \"y\": 128,\n"
"          \"w\": 150,\n"
"          \"h\": 90,\n"
"          \"props\": {\n"
"            \"label\": \"Uptime\",\n"
"            \"pin\": \"Panel_Uptime_s\",\n"
"            \"unit\": \" s\",\n"
"            \"decimals\": 0,\n"
"            \"min\": 0,\n"
"            \"max\": 1000000,\n"
"            \"color\": \"#CBD5E1\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"tag_count_label\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 220,\n"
"          \"y\": 130,\n"
"          \"w\": 270,\n"
"          \"h\": 74,\n"
"          \"props\": {\n"
"            \"label\": \"Tags, layout, and scripts can be saved to RAM or Flash from the browser.\",\n"
"            \"color\": \"#CBD5E1\",\n"
"            \"fontSize\": 17\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"run_diag\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 520,\n"
"          \"y\": 128,\n"
"          \"w\": 102,\n"
"          \"h\": 90,\n"
"          \"props\": {\n"
"            \"label\": \"Run\",\n"
"            \"pin\": \"Motor_Running\",\n"
"            \"color\": \"#22C55E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"fault_diag\",\n"
"          \"type\": \"led\",\n"
"          \"x\": 650,\n"
"          \"y\": 128,\n"
"          \"w\": 102,\n"
"          \"h\": 90,\n"
"          \"props\": {\n"
"            \"label\": \"Fault\",\n"
"            \"pin\": \"Fault_Active\",\n"
"            \"color\": \"#F43F5E\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"memory_note\",\n"
"          \"type\": \"label\",\n"
"          \"x\": 38,\n"
"          \"y\": 250,\n"
"          \"w\": 690,\n"
"          \"h\": 74,\n"
"          \"props\": {\n"
"            \"label\": \"Open http://192.168.4.1 after joining WiFi SSID PiLab-Panel. Use Load from LCD to pull the running demo into the browser editor.\",\n"
"            \"color\": \"#94A3B8\",\n"
"            \"fontSize\": 18\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"main_btn2\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 36,\n"
"          \"y\": 374,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"MainPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"MAIN\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#0EA5E9\"\n"
"          }\n"
"        },\n"
"        {\n"
"          \"id\": \"process_btn2\",\n"
"          \"type\": \"button\",\n"
"          \"x\": 206,\n"
"          \"y\": 374,\n"
"          \"w\": 150,\n"
"          \"h\": 58,\n"
"          \"events\": {\n"
"            \"onClick\": \"ProcessPage_Click\"\n"
"          },\n"
"          \"props\": {\n"
"            \"label\": \"PROCESS\",\n"
"            \"buttonMode\": \"script\",\n"
"            \"color\": \"#16A34A\"\n"
"          }\n"
"        }\n"
"      ]\n"
"    }\n"
"  ]\n"
"}\n"
;

const char *hmi_layout_default_json(void) { return s_default_layout; }

static bool hmi_layout_json_is_usable(const char *json, int *out_version)
{
    if (out_version) *out_version = 0;
    if (!json || !json[0]) return false;

    cJSON *root = cJSON_Parse(json);
    if (!root) return false;

    const cJSON *ver = cJSON_GetObjectItemCaseSensitive(root, "version");
    if (cJSON_IsNumber(ver) && out_version) *out_version = ver->valueint;

    const cJSON *widgets = cJSON_GetObjectItemCaseSensitive(root, "widgets");
    const cJSON *objects = cJSON_GetObjectItemCaseSensitive(root, "objects");
    const cJSON *pages = cJSON_GetObjectItemCaseSensitive(root, "pages");
    bool ok = cJSON_IsArray(widgets) || cJSON_IsArray(objects) || cJSON_IsArray(pages);

    cJSON_Delete(root);
    return ok;
}

esp_err_t hmi_layout_store_load(char **out_json)
{
    if (!out_json) return ESP_ERR_INVALID_ARG;
    *out_json = NULL;

    FILE *f = fopen(HMI_LAYOUT_PATH, "rb");
    if (!f) {
        ESP_LOGW(TAG, "No saved layout yet; using embedded default");
        *out_json = strdup(s_default_layout);
        return *out_json ? ESP_OK : ESP_ERR_NO_MEM;
    }

    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    rewind(f);
    if (len <= 0 || len > HMI_MAX_LAYOUT_BYTES) {
        fclose(f);
        ESP_LOGE(TAG, "Saved layout length is invalid: %ld; using embedded default", len);
        *out_json = strdup(s_default_layout);
        return *out_json ? ESP_OK : ESP_ERR_NO_MEM;
    }

    char *buf = (char *)calloc(1, (size_t)len + 1);
    if (!buf) { fclose(f); return ESP_ERR_NO_MEM; }

    size_t n = fread(buf, 1, (size_t)len, f);
    fclose(f);
    if (n != (size_t)len) {
        free(buf);
        ESP_LOGE(TAG, "Saved layout read failed; using embedded default");
        *out_json = strdup(s_default_layout);
        return *out_json ? ESP_OK : ESP_ERR_NO_MEM;
    }

    int version = 0;
    if (!hmi_layout_json_is_usable(buf, &version)) {
        ESP_LOGE(TAG, "Saved layout JSON is invalid/unusable; using embedded default");
        free(buf);
        *out_json = strdup(s_default_layout);
        return *out_json ? ESP_OK : ESP_ERR_NO_MEM;
    }

    // Important: accept designer-created layouts from newer web app versions.
    // Earlier prototypes only accepted version 2 and silently replaced anything
    // else with the embedded demo. The current Vue designer saves version 3, so
    // the old check made Save to Panel appear to fail after reboot/reload.
    ESP_LOGI(TAG, "Loaded saved HMI layout: %ld bytes, version=%d", len, version);
    *out_json = buf;
    return ESP_OK;
}

esp_err_t hmi_layout_store_save(const char *json)
{
    if (!json) return ESP_ERR_INVALID_ARG;

    size_t len = strlen(json);
    if (len == 0 || len > HMI_MAX_LAYOUT_BYTES) {
        ESP_LOGE(TAG, "Refusing to save invalid HMI layout length: %u", (unsigned)len);
        return ESP_ERR_INVALID_SIZE;
    }

    int version = 0;
    if (!hmi_layout_json_is_usable(json, &version)) {
        ESP_LOGE(TAG, "Refusing to save invalid/unusable HMI layout JSON");
        return ESP_ERR_INVALID_ARG;
    }

    // Write atomically enough for SPIFFS: write a temp file, then replace the
    // active file. This prevents a power loss or short write from leaving a
    // truncated hmi_layout.json that later renders garbage.
    const char *tmp_path = "/spiffs/hmi_layout.tmp";
    FILE *f = fopen(tmp_path, "wb");
    if (!f) {
        ESP_LOGE(TAG, "Failed to open temp layout file for write");
        return ESP_FAIL;
    }

    size_t n = fwrite(json, 1, len, f);
    int close_rc = fclose(f);
    if (n != len || close_rc != 0) {
        remove(tmp_path);
        ESP_LOGE(TAG, "Failed to write complete HMI layout: wrote=%u expected=%u close=%d",
                 (unsigned)n, (unsigned)len, close_rc);
        return ESP_FAIL;
    }

    remove(HMI_LAYOUT_PATH);
    if (rename(tmp_path, HMI_LAYOUT_PATH) != 0) {
        remove(tmp_path);
        ESP_LOGE(TAG, "Failed to promote temp HMI layout file");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "Saved HMI layout: %u bytes, version=%d", (unsigned)len, version);
    return ESP_OK;
}

esp_err_t hmi_layout_store_reset_default(void)
{
    return hmi_layout_store_save(s_default_layout);
}
